import React from "react";
import { BookOpen, Search, ArrowRight, Zap, Shield, Brain } from "lucide-react";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Knowledge Hub | Logic Intelligence Technologies",
  description: "Centralized hub for understanding AI concepts, capabilities, and product guides at Logic Intelligence Technologies.",
};

export default function KnowledgeBasePage() {
  const articles = [
    { title: "VoiceShield Integration Guide", desc: "Learn how to deploy real-time anti-spoofing in your VoIP stack.", icon: Shield },
    { title: "Understanding LLM Latency", desc: "Best practices for achieving sub-200ms inference on edge nodes.", icon: Zap },
    { title: "Retrieval-Augmented Gen", desc: "How to safely connect your enterprise databases to our AI Assistant.", icon: Brain },
  ];

  return (
    <div className="min-h-screen bg-[#030712] text-slate-100 selection:bg-emerald-500 selection:text-slate-950 pt-32 pb-24">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(16,185,129,0.1),_transparent_50%)]" />

      <div className="relative z-10 mx-auto max-w-5xl px-4 sm:px-6">
        
        {/* Header Section */}
        <div className="text-center space-y-6 mb-16">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl border border-slate-800 bg-slate-900/50 shadow-2xl backdrop-blur-xl mb-4">
            <BookOpen className="w-8 h-8 text-emerald-400" />
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-[0.12em] text-white uppercase">
            AI Knowledge Hub
          </h1>
          <p className="text-sm sm:text-base text-slate-400 leading-relaxed max-w-2xl mx-auto">
            Everything you need to deploy, scale, and secure enterprise AI systems. Browse our documentation, architectural deep dives, and glossary of terms.
          </p>

          {/* Fake Search Bar */}
          <div className="max-w-xl mx-auto relative mt-8">
            <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
              <Search className="h-5 w-5 text-emerald-500/50" />
            </div>
            <input
              type="text"
              placeholder="Search documentation, guides, and APIs..."
              className="w-full pl-12 pr-4 py-4 rounded-xl bg-slate-900/80 border border-slate-800 text-sm text-slate-100 placeholder:text-slate-500 font-mono focus:outline-none focus:border-emerald-500/50 focus:ring-1 focus:ring-emerald-500/30 transition-colors shadow-2xl"
              readOnly
            />
          </div>
        </div>

        {/* Categories */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {articles.map((article, idx) => (
            <div key={idx} className="p-6 rounded-2xl border border-slate-800 bg-slate-900/50 backdrop-blur-xl hover:border-emerald-500/30 transition-colors group cursor-pointer">
              <article.icon className="w-6 h-6 text-emerald-400 mb-4" />
              <h3 className="text-sm font-mono font-bold tracking-widest text-white uppercase mb-2">
                {article.title}
              </h3>
              <p className="text-sm text-slate-400 leading-relaxed mb-4">
                {article.desc}
              </p>
              <div className="text-xs font-mono font-bold text-emerald-400 flex items-center gap-2 group-hover:gap-3 transition-all">
                Read Article <ArrowRight className="w-3 h-3" />
              </div>
            </div>
          ))}
        </div>

        {/* Glossary Section */}
        <div className="rounded-2xl border border-emerald-900/50 bg-emerald-950/10 backdrop-blur-xl p-8 sm:p-10 shadow-2xl">
          <h2 className="text-lg font-mono font-bold tracking-widest text-white uppercase mb-6 flex items-center gap-3">
            <Brain className="w-5 h-5 text-emerald-400" />
            Enterprise AI Terminology
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h4 className="text-sm font-mono font-bold text-emerald-400 mb-2">Deepfake Audio</h4>
              <p className="text-sm text-slate-400">Synthetic audio generated by deep neural networks mimicking human voices. Countered by our VoiceShield infrastructure.</p>
            </div>
            <div>
              <h4 className="text-sm font-mono font-bold text-emerald-400 mb-2">Inference Latency</h4>
              <p className="text-sm text-slate-400">The time taken by an AI model to process input and return an output. Our models operate strictly under 200ms.</p>
            </div>
            <div>
              <h4 className="text-sm font-mono font-bold text-emerald-400 mb-2">Zero-Day Attacks</h4>
              <p className="text-sm text-slate-400">Novel, previously unseen AI attacks or spoofing attempts. We utilize dynamic anomaly detection to block these.</p>
            </div>
            <div>
              <h4 className="text-sm font-mono font-bold text-emerald-400 mb-2">R.A.G.</h4>
              <p className="text-sm text-slate-400">Retrieval-Augmented Generation. Supplying an LLM with your specific business data for highly accurate answers.</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
