-- ============================================================
-- VoiceShield Integration: Core Telemetry Tables
-- Migration: 20260919000001_voiceshield_core_tables.sql
-- ============================================================
-- These tables handle the core VoiceShield telemetry, forensics,
-- and session tracking. Namespaced with `voice_` prefix as requested.
-- ============================================================

-- 1. Voice Sessions
CREATE TABLE IF NOT EXISTS voice_sessions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id      UUID REFERENCES profiles(id) ON DELETE SET NULL, -- Links to LIT profile
  started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at        TIMESTAMPTZ,
  client_info     JSONB NOT NULL DEFAULT '{}'::jsonb, -- IP, User-Agent, etc.
  risk_summary    JSONB NOT NULL DEFAULT '{}'::jsonb, -- Aggregate stats for session
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'aborted', 'blocked')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Voice Detection Events (Real-time scoring per chunk)
CREATE TABLE IF NOT EXISTS voice_detection_events (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id          UUID NOT NULL REFERENCES voice_sessions(id) ON DELETE CASCADE,
  chunk_index         INTEGER NOT NULL,
  timestamp_ms        BIGINT NOT NULL,
  spoof_probability   FLOAT NOT NULL,
  risk_level          TEXT NOT NULL CHECK (risk_level IN ('low', 'medium', 'high')),
  features_snapshot   JSONB, -- LFCC/Mel metrics
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Voice Threat Alerts (When a session trips a high-risk threshold)
CREATE TABLE IF NOT EXISTS voice_threat_alerts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      UUID NOT NULL REFERENCES voice_sessions(id) ON DELETE CASCADE,
  alert_type      TEXT NOT NULL CHECK (alert_type IN ('high_probability', 'phase_discontinuity', 'vocoder_artefact')),
  severity        TEXT NOT NULL CHECK (severity IN ('warning', 'critical')),
  notified        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Voice Forensic Jobs (Async Celery Pipeline)
CREATE TABLE IF NOT EXISTS voice_forensic_jobs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id      UUID REFERENCES profiles(id) ON DELETE SET NULL,
  file_url        TEXT NOT NULL, -- S3/R2 URL
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  error_message   TEXT,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Voice Forensic Results (THROUGHPUTS XAI Summaries)
CREATE TABLE IF NOT EXISTS voice_forensic_results (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id          UUID NOT NULL REFERENCES voice_forensic_jobs(id) ON DELETE CASCADE,
  overall_risk    TEXT NOT NULL CHECK (overall_risk IN ('low', 'medium', 'high')),
  peak_spoof      FLOAT NOT NULL,
  xai_summary     TEXT NOT NULL, -- The text generated by THROUGHPUTS
  splice_detected BOOLEAN NOT NULL DEFAULT FALSE,
  segments        JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_voice_events_session ON voice_detection_events(session_id);
CREATE INDEX IF NOT EXISTS idx_voice_sessions_profile ON voice_sessions(profile_id);
CREATE INDEX IF NOT EXISTS idx_voice_forensic_profile ON voice_forensic_jobs(profile_id);

-- Enable RLS
ALTER TABLE voice_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_detection_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_threat_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_forensic_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_forensic_results ENABLE ROW LEVEL SECURITY;

-- Base RLS Policies: Users can only see their own telemetry
CREATE POLICY "Users can view their own sessions" ON voice_sessions FOR SELECT USING (profile_id = auth.uid());
CREATE POLICY "Users can view their own events" ON voice_detection_events FOR SELECT USING (session_id IN (SELECT id FROM voice_sessions WHERE profile_id = auth.uid()));
CREATE POLICY "Users can view their own alerts" ON voice_threat_alerts FOR SELECT USING (session_id IN (SELECT id FROM voice_sessions WHERE profile_id = auth.uid()));
CREATE POLICY "Users can view their own forensic jobs" ON voice_forensic_jobs FOR SELECT USING (profile_id = auth.uid());
CREATE POLICY "Users can view their own forensic results" ON voice_forensic_results FOR SELECT USING (job_id IN (SELECT id FROM voice_forensic_jobs WHERE profile_id = auth.uid()));

-- Only Service Role can insert/update (Backend processes)
CREATE POLICY "Service Role Full Access Sessions" ON voice_sessions USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Events" ON voice_detection_events USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Alerts" ON voice_threat_alerts USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Jobs" ON voice_forensic_jobs USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Results" ON voice_forensic_results USING (true) WITH CHECK (true);
